### ISSUE TITLE
Make this installable via composer 

### ISSUE THREAD

**Issue by memdev** [reportico-web/reportico#10]
Hi,
is there a chance to make this project available via composer, like the Laravel or Yii version?
This would be great!

**Comment by reportico-web** [comment]
Hi there, would love to do this, would make a lot of sense.....

I personally am not an expert with composer, is it just a case of adding a composer.json file and do you think it could be added just to the existing github project and that would then link it into packagist?

**Comment by daN4cat** [comment]
Hopefully the PR I just created solves this issue, but it needs a step from your side @reportico-web.

**Comment by daN4cat** [comment]
Also add the automatic update support to Packagist, see in https://packagist.org/about section "How to update packages?".

**Comment by reportico-web** [comment]
Hi there, I think i did this, and managed to use composer to donwload .. can you check it's ok from where you are?

**Comment by daN4cat** [comment]
Thanks a lot, I'll test it over the weekend.
I needed it because I'm working on an integration of reportico in codeigniter (check my github repos) and I wanted to use composer to allow the download adding a dependency on reportico with composer.

**Comment by daN4cat** [comment]
I could pull reportico code to https://github.com/daN4cat/codeigniter-reportico having it as dependency in composer.json.
So all seems fine from that perspective. However I would need to test that code and the fact that could work fine. But it's WIP at the moment.

**Comment by reportico-web** [comment]
Ok good luck, let me know if i can help

**Comment by daN4cat** [comment]
@reportico-web most likely I would need to understand how to embed it properly. Also if there is a way to style reportico with flavours of Bootstrap 3. For instance in OSPOS (see #13) I introduced Bootswatch themes, one can select various Bootstrap 3 based themes from the application.

**Comment by reportico-web** [comment]
Closed as imminent beta now works under composer

composer create-project reportico-web/reportico

(also larave and yii modules much improved to integrate with composer )

**Comment by daN4cat** [comment]
@reportico-web I noticed that installing the beta 6.0.0 installs Symphony under vendor. Is that required?
