### ISSUE TITLE
Upgrade to Smarty 3 and include it via composer

### ISSUE THREAD

**Issue by memdev** [reportico-web/reportico#12]
I wanted to embed Reportico into my existing project and went into problems with Smarty.
I use Smarty 3 in my project and Reportico has Smarty 2 included. This produces conflicts when embedding Reportico.

It would be great if you could upgrade to Smarty 3, ideally by pulling it in via composer.
Also, Reportico should check if Smarty is already available and only include it, if not.

**Comment by daN4cat** [comment]
@memdev what about suggesting a solution for Composer to solve Smarty dependency in composer.json?
If we all help the solution will get better...

**Comment by reportico-web** [comment]
Thanks @memdev and @daN4cat ... would be happy to merge in any commits or take any guidance on this as im not  familiar with composer to that level.

**Comment by daN4cat** [comment]
@reportico-web is the list of dependency somewhere?
I mean what other 3rd party libraries do you use in Reportico?

**Comment by daN4cat** [comment]
About 3rd party point please check #13 as there is a link between the two.

**Comment by reportico-web** [comment]
Reportico depends on several libraries .. but ive customised most of them .. however Smarty is probably ok to include as a dependency without changes .. 
other dependencies 
FPDF & TCPDF PDF Generator (but ive customimsed these)
adodb ( customised slightly )
Smarty
nvd3.js d3.js ( for html charts )
pchart ( for pdf charts )
bootstrap 2/3 /jquery
download.js
datatables
select2

Think thats it ...

**Comment by daN4cat** [comment]
@reportico-web have you tried reportico with Smarty3? That's what @memdev was asking about in the first instance.

**Comment by reportico-web** [comment]
not yet i havent .. i'll put that in the plan

**Comment by reportico-web** [comment]
Imminent beta release now is composer based and replaces Smarty with Twig

Installable with 
composer create-project reportico-web/reportico

**Comment by daN4cat** [comment]
Good. Yesterday I was looking again into this as I didn't have much time so far.
