### ISSUE TITLE
v4.3 - compiled_templates_folder parameter is never fed to Smarty to set the compiled template path

### ISSUE THREAD

**Issue by nmcgann** [reportico-web/reportico#3]
Smarty is fed with `$smarty->compile_dir = find_best_location_in_include_path( "templates_c" );` This has no knowledge of `$compiled_templates_folder` parameter.

Means that the compile dir can't be set outside the reportico file structure or be anything but `templates_c`.

**Comment by reportico-web** [comment]
Closed due to imminent composer-based beta release now uses twig for templating

composer create-project reportico-web/reportico
