### ISSUE TITLE
Reportico 6.0.11 is not support PHP 7.4

### ISSUE THREAD

**Issue by rt-betty** [reportico-web/reportico#33]
Upgrading to PHP7.4 reports the following error.
Fatal Error: /opt/tk/core/web/temp_php_script/reportico2/src/XmlReader.php Line 1487 - Function get_magic_quotes_gpc() is deprecated

**Comment by reportico-web** [comment]
Hi there

Are you able to temporarily add the following to the top of that file .... and can  you tell me are you using reportico just by installing with composer or zip file or as part of a plugin like Joomla?

```
if ( !function_exists("get_magic_quotes_gpc") ) {
    function get_magic_quotes_gpc() {
        return false;
    }
}
```

Peter

**Comment by rt-betty** [comment]
> 
> 
> Hi there
> 
> Are you able to temporarily add the following to the top of that file .... and can you tell me are you using reportico just by installing with composer or zip file or as part of a plugin like Joomla?
> 
> ```
> if ( !function_exists("get_magic_quotes_gpc") ) {
>     function get_magic_quotes_gpc() {
>         return false;
>     }
> }
> ```
> 
> Peter

**Comment by rt-betty** [comment]
It is installed using composer.  
I'm using it for commercial purposes.  can I change the source code?

**Comment by reportico-web** [comment]
Hi there .. Reportico is under MIT license so you you are free to modify as you please for any purposes.

**Comment by rt-betty** [comment]
Hi Peter,
The license I see on the following URL is GPL.  It is not allowed to modify source code. 
http://www.reportico.org/site/index.php/reportico-license
