### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by phpfui** [reportico-web/reportico#39]
Looks like this project may no longer be supported.  I am looking for a report generator for PHP and MySQL.  But on PHP 8.0 (best version ever!) and see that this package has not been updated (bad ordering of default parameters is the first issue I see) for PHP 8.0.

I would be happy to help move the project forward if I decide to use it, but not sure what the long term prospects are.  As I am still in the looking mode, I don't want to commit to something that may be abandoned, but also might be willing to take it over, depending on what else is out there.

I do like the general architecture and I see that there a lot of potential in this code base, so it would be shame to lose it.

Your thoughts?

**Comment by reportico-web** [comment]
Hi there

Thanks for the port. The project is not certainly not dead, but it's very hard to find the time to keep it up to date.
It should be up to date as far as 7.x but i think it should be simple to make it compatible with PHP 8 assuming the composer dependencies all are compatible too!

If you do get it working I will gladly merge in the commits and happy to collaborate on this, any help you need to this let me know .. but this certainly addressing quickly as a project I am using it for will soon be on PHP 8 so I will be doing this soon anyway if you dont.

Peter

**Comment by phpfui** [comment]
Peter,

Thanks for the response. Still evaluating things. If we decide to go with
Reportico, I will certainly be submitting PRs.

Bruce

**Comment by kentchang84** [comment]
Looking forward PHP 8.0 support.

**Comment by mrbigmtl** [comment]
Any idea if and/or when PHP 8 support will be available?

**Comment by reportico-web** [comment]
Hi there .. support for version 8 was started and  I think the latest version 8.0.1 of this project fixes a large amount of the issues .. it needs testing further but your message should encourage at least some continuation of this.. but worth trying 8.0.1

**Comment by topwebs** [comment]
How would you update from version 6.0.10 to 8.0.1?
