### ISSUE TITLE
I am trying to get the following link to work properly.  localhost/reportico-7.0/index.php?r=reportico/mode/execute&project=PMTTS&target_format=PDF&new_reportico_window=1&report=ContactList.xml'

### ISSUE THREAD

**Issue by lloyd966** [reportico-web/reportico#40]
I am hoping that you can help me out. I have install the latest version of Reportico. I am trying to get the following link to work properly.

localhost/reportico-7.0/index.php?r=reportico/mode/execute&project=PMTTS&target_format=PDF&new_reportico_window=1&report=ContactList.xml'

Currently it opens a screen with a list of all available reports within the PMTTS Project. I want to bypass this screen and any other screens, and show the screen display the report.

Any help with this would be greatly appreciated.

Thank you.

Lloyd

**Comment by reportico-web** [comment]
Ok I think you may have been yii before .. you dont need the r=and should be able to add execute_mode=EXECUTE .. instead

**Comment by lloyd966** [comment]
Below is the code I created based on your recent response.

            http://localhost/reportico-7.0/index.php/execute_mode=EXECUTE&project=PMTTS&report=ContactList.xml

and when run this code in my browser it displays the Reportico Administration Page.

Can you verify my code and let me know if this code is correct or if not, can you please supply me with the right code.

Thank you

Lloyd

**Comment by lloyd966** [comment]
Just to clarify.

I have created a project using the Yii2 Framework and recently installed your yii2-reportico extension using composer. 

As the current version of your extension is using an older version of your Reportico software, and I am using PHP 7.4.9, 
which causes problems with the current version of yii2-reportico, I decided to install the latest version of Reportico 
separate from Yii2.

Is there any possibility that you will update the yii2-reportico extension with the latest version of Reportico, and if so do you have
any idea when this might be done.

**Comment by lloyd966** [comment]
Any help would be greatly appreciated. I need to get this to work.


Below is the code I created based on your recent response.

        http://localhost/reportico-7.0/index.php/execute_mode=EXECUTE&project=PMTTS&report=ContactList.xml
and when run this code in my browser it displays the Reportico Administration Page.

Can you verify my code and let me know if this code is correct or if not, can you please supply me with the right code.

Thank you

Lloyd

**Comment by reportico-web** [comment]
Can you try replacing the slash before execute_mode with a question mark

**Comment by lloyd966** [comment]
The following code

http://localhost/reportico-7.0/index.php?execute_mode=EXECUTE&project=PMTTS&report=ContactList.xml

produces the following error

        Main Report Query - Error: Query Failed

        SELECT FROM WHERE 1 = 1

        Status 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the 
        right syntax to use near 'FROM WHERE 1 = 1' at line 2

but when I run the report from the project menu the report works perfectly

Any idea on how to fix this???????

**Comment by reportico-web** [comment]
Hi lloyd

Before I look at this indepth can you change report= to xmlin=  .. also try with and without the .xml extenstion... the error you get now is because it cant open either the project forlder or the report. 

In reportico7.0 there is a better way where you create a php file containing the project and report by creating in the reportico folder say a file myreport.php that looks like this...
```
<?php
require_once('/vendor/autoload.php');
\Reportico\Engine\Builder::build()
    ->project("PMTTS")
    ->load("ContactList")
    ->execute();
?>
```

Although id like  to get the former working before trying this because you might have the same problems 
Peter

**Comment by lloyd966** [comment]
Hi Peter

As per your suggestion, I tried the following 

http://localhost/reportico-7.0/index.php?execute_mode=EXECUTE&project=PMTTS&xmlin=ContactList.xml

and **IT WORKED**. 

I would really would like to be able to access Reportico as a Yii2 extension, rather than installing and accessing Reportico  separately.

Any chance that the Yii2-reportico extension will be updated to use the latest version of Reportico (ie: version 7)

Thank you so much for all your help in resolving my issue.

Regards,

Lloyd

**Comment by lloyd966** [comment]
Hi Peter

Below is the code I am using to create a pdf report

http://localhost/reportico-7.0/index.php?execute_mode=EXECUTE&project=PMTTS&xmlin=ContactList.xml

Is there any code I can add to the above to open a new tab (ie: window) to display the pdf report rather than the report
being created in my download folder?

Regards,

Lloyd

**Comment by reportico-web** [comment]
Hi Lloyd ..

If you got to your reportico folder and edit start.php and go to line 278 you will see a commented out line

```
//$reportico->pdf_delivery_mode = "DOWNLOAD_SAME_WINDOW";
```

uncomment this and change it to 

```
$reportico->pdf_delivery_mode = "INLINE";
```

**Comment by lloyd966** [comment]
Hi Peter

The change worked.

Thank you

Lloyd
