### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by daN4cat** [reportico-web/reportico#41]
Hi,

How can I report a security issue?
I wrote an email to the info@ from the web page but I've got no answer.

Please reply.

**Comment by reportico-web** [comment]
Hi I should have seen it.. I'll check my mailbox..  but can you resend to the info at reportico org  email . but am keen to understand it

**Comment by daN4cat** [comment]
I've resent the email last night.

**Comment by reportico-web** [comment]
Thanks I'll have a look later

**Comment by daN4cat** [comment]
Have you been able to reproduce the issue?

**Comment by reportico-web** [comment]
Hi there .. time is against me but plan to look this coming weekend

**Comment by reportico-web** [comment]
Hi Ive had a look at this and yes you have found a bug that hopefully i've fixed .. apologies for this issue. 

I have a fix but before I release it, can I ask you to make the changes locally to check it out and then I'll make a new release  ..

So underneath reportico folder can you replace the file vendor/reportico-web/reportico/src can you replace the attached Authenticator.php with the attached zipped version

[secfix.zip](https://github.com/reportico-web/reportico/files/6872564/secfix.zip)

**Comment by daN4cat** [comment]
I'm coming back from holidays today and test it later or tomorrow.

**Comment by daN4cat** [comment]
Thanks for the fix.

**Comment by daN4cat** [comment]
Hi, that patch fixed the issue. Please add it and issue a new version.
