### ISSUE TITLE
v4.4 - // shown on top of page

### ISSUE THREAD

**Issue by daN4cat** [reportico-web/reportico#7]
Just installed 4.4 and added the configuration and projects I had with 4.2 and I noticed a // printed on the top left:

![image](https://cloud.githubusercontent.com/assets/636048/14570663/5900374c-033d-11e6-9f47-04415bd51ee5.png)

Minor: the version is reported 4.3 even if it's 4.4.

**Comment by daN4cat** [comment]
Clicking on admin login without inserting any password just keeps increasing the // on the top line.

**Comment by reportico-web** [comment]
Hi there .. im sorry for such a late reply.. if you are still iterested in getting this working i'd like to help..
did you install the 4.4 from  github clone or from sourceforge?

I just pulled the 4.4 version and im not seeing this. However I just pushed a load of changes in to 4.4 to make it compatible with PHP 7.0.

I would say that 4.3 is the more stable of the releases and maybe you might not experience this problem with that, but i would be interested in finding this out. Are you able to send me a copy of the HTML source of the page that contains the / character?

**Comment by daN4cat** [comment]
I used the sourceforge 4.4 zip from here: https://sourceforge.net/projects/reportico/files/

If github one is fine I'll update my installation with that one. Unless it's unstable and you suggest to really fall back to 4.3

**Comment by reportico-web** [comment]
ok thanks ...i just tried the one from sourceforge and it doesnt show the slashes... i wish i could recreate this.. what version of PHP are you using and is your web server apache or microsoft?

**Comment by daN4cat** [comment]
OK, I will try again from scratch and see what happens.

**Comment by daN4cat** [comment]
Sorry for my belated reply.

I found the root cause of the //, somehow in the config.php on the first line I had //<?php.
Of course the // is not right and was printed out.

I have no idea where that came from, but it's sorted.

I'm currently using the latest 4.4 from the branch here.
